### PR TITLE
Home page updated

### PR DESCRIPTION
**Pull request by gabru-md**
homepage of the website has been updated.
home.htm has been added to do so.

please go through it and merge if possible!

- gabru-md

### CODE REVIEW

**Comment by gabru-md** [comment]
@lakshay365 PS:

notes.htm has also been created.
I have some idea in mind. But the layout is ready so i am uploading it. 

Look through it and let me know if you can merge 

- gabru-md

**Comment by gabru-md** [comment]
@lakshay365 
Kindly note the following as major changes in the files: notes.htm ( created and updated ) and main.js( updated for notes.htm )

notes.htm has been further updated.
main.js updated.
the javascript has been further developed according to the site's 

Look through it and let me know if you can merge!

- gabru-md

**Comment by lakshay365** [comment]
@gabru-md I'll merge this branch later with the master after a few changes.

**Comment by gabru-md** [comment]
what changes brother ?

**Pull request merged**
